version: '3'
services:
  projectbox-postgres:
    image: postgres:15-alpine
    container_name: projectbox-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=projectbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  projectbox-redis:
    container_name: projectbox-redis
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379